### PR TITLE
Extend hid descriptor maximum to make international keyboard

### PR DESCRIPTION
**Pull request by yswallow**
This enables sending keycode 0x87( e.g. backslash in Japanese keyboard ) etc.

### CODE REVIEW

**Comment by dhalbert** [comment]
Perhaps we should make this 255, since there are other possible keys that are greater. See https://www.usb.org/sites/default/files/documents/hut1_12v2.pdf, page 59. Do you know if there's some reason not to do that?

**Comment by yswallow** [comment]
While I don't know much about HID devices, I found three points.

1. [Adafruit_CircuitPython_HID/keycode.py](https://github.com/adafruit/Adafruit_CircuitPython_HID/blob/master/adafruit_hid/keycode.py) is up to 0x65, the same.
2. This PullReq is up to 0x89, but Japanese MUHENKAN key is 0x91, not enough.
3. keycode 0xE0 and greater are modifier keys. So no need to append this usage page.


I tested 0xB0 to 0xCE, only 0xB9 and 0xBC are effective. ( I mean, if the keys don't work properly, we should not extend the range. )

0xB9 is defined as `keypad }`, but opened `open...` menu.
0xBC is defined as `keypad A`, but opened `save...` menu.

**Comment by tannewt** [comment]
This change looks good to me. @dhalbert is on vacation and may want to follow up later.

**Review by tannewt — APPROVED** [review]
Thanks @yswallow

**Pull request merged**
