### PR TITLE
Disconnect when restarting HID example; provide default HID descriptor

### PR DESCRIPTION
**Pull request by dhalbert**
A connection doesn't re-pair properly if this example is restarted and the peer thinks the connection is still ongoing. So this change closes all connections first.

@tannewt I'm not sure this is the best solution, but I'm not sure it's possible to know which connection is the "right" one to close. Also, would this close the CircuitPython service connection, or is that hidden?

Also I removed setting the complete name, but this is a matter of taste. It doesn't always appear in lists of devices to pair: sometimes one sees a cached name. It depends on the OS.

### CODE REVIEW

**Comment by dhalbert** [comment]
@tannewt I moved the big HID descriptor out of the example and into `hid.py` as a default descriptor. That could probably be improved (like selecting which devices you want), but it's good for now, and it makes example code and Guide code simpler.

**Comment by dhalbert** [comment]
I think it's a good idea in the long run to move the descriptor, but I'm a bit worried about increasing the size of the frozen HID library. Could we do that as a longer-term goal? If we merge this PR now then we can publish JP's BLE HID guide right away.

**Comment by TheKitty** [comment]
Per Dan, merging now and the descriptor move will be considered in a later revision

**Comment by tannewt** [comment]
@TheKitty Please don't merge if I've asked something and not done it myself. I may have another solution. Please ping me instead.

For now, this is ok. I'll think on where it should go.

**Pull request merged**
