### PR TITLE
Modified ManufacturerDataField to return a namedtuple if possible

### PR DESCRIPTION
**Pull request by alexwhittemore**
I'm definitely not convinced this covers all cases, nor am I convinced it's non-breaking, so I'm interested in feedback (but it does work neatly in my case).

If a given `Advertisement` subclass is defined with multiple fields in a single `ManufacturerDataField`, the current class requires it to have an array of `field_names`, which heretofore are unused.

This PR 1) enforces that `field_names` must be formatted properly for a namedtuple (i.e. no spaces, probably plenty of other things) and 2) returns a `MDFTuple` instead of a regular tuple, with fields named as defined. 

Mostly, I'm not sure when lines 285+ come into play, and whether they ought to be covered by the namedtuple modification.

### CODE REVIEW

**Comment by alexwhittemore** [comment]
For linky goodness, this would fix #114

**Comment by jposada202020** [comment]
@alexwhittemore Hello alex, do you have any test code, I could test the changes to move this forward but I would like to know what were your test conditions. Thanks :)

**Comment by jposada202020** [comment]
@tannewt :) now that you are working on the BLE, what do you are your thoughts regarding this PR?

Thanks

**Review by tannewt — APPROVED** [review]
This looks good to me!

**Pull request merged**
